parameters:
#    parroquia_agenda.example.class: Parroquia\AgendaBundle\Example

services:
#    parroquia_agenda.example:
#        class: %parroquia_agenda.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
