imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: messages.yml }    

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'ParroquiaHomeBundle:Form:fields.html.twig'    
            - 'LexikFormFilterBundle:Form:form_div_layout.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to:   "\.less$"
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
    assets:
        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.9.1.js
            output: js/jquery.js        

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  smtp
    encryption: tls
    auth_mode:  login
    host:       email-smtp.us-east-1.amazonaws.com
    port:       25
    username:   AKIAJRJVGXXDQZLSCHKA
    password:   AuOuRnjvqm50pOwA4/zQFmjbrazo1kRBBeNXa4gVe3vX    

knp_snappy:
    pdf:
        enabled:    true
        binary:     %kernel.root_dir%/../vendor/h4cc/wkhtmltopdf-i386/bin/wkhtmltopdf-i386
        options:    []
    image:
        enabled:    true
        binary:     %kernel.root_dir%/../vendor/h4cc/wkhtmltoimage-i386/bin/wkhtmltoimage-i386
        options:    []

stfalcon_tinymce:
    theme:
        # Simple theme: same as default theme
        simple: ~
        # Advanced theme with almost all enabled plugins
        advanced:
             plugins:
                 - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                 - "searchreplace wordcount visualblocks visualchars code fullscreen"
                 - "insertdatetime media nonbreaking save table contextmenu directionality"
                 - "emoticons template paste textcolor"
             toolbar1: "insertfile undo redo | styleselect | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent"
             toolbar2: "print preview | link image media | forecolor backcolor emoticons | stfalcon | example | removeformat"
             image_advtab: true
             insertdatetime_formats: ["%%H:%%M:%%S", "%%d-%%m-%%Y", "%%I:%%M:%%S %%p", "%%d/%%m/%%Y"]
             
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Parroquia\UserBundle\Entity\User
    from_email:
        address:        cache@cache.cl
        sender_name:    Parroquia - Sistema   
        
services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }