parameters:
#    parroquia_home.example.class: Parroquia\HomeBundle\Example

services:
    parroquia_home.menu_builder:
        class: Parroquia\HomeBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory","@security.context"]

    parroquia_home.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: parroquia_home.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }
            
    parroquia_home.menu.user:
        class: Knp\Menu\MenuItem
        factory_service: parroquia_home.menu_builder
        factory_method: createUserMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: user }
            
    parroquia_home.menu.breadcrumb:
        class: Knp\Menu\MenuItem
        factory_service: parroquia_home.menu_builder
        factory_method: createBreadcrumbMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: breadcrumb }