parameters:
#    parroquia_correo.example.class: Parroquia\CorreoBundle\Example

services:
#    parroquia_correo.example:
#        class: %parroquia_correo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
