parroquia_comunidad_homepage:
    pattern:  /
    defaults: { _controller: ParroquiaComunidadBundle:Default:index }

ParroquiaComunidadBundle_persona:
    resource: "@ParroquiaComunidadBundle/Resources/config/routing/persona.yml"
    prefix:   /personas
    
ParroquiaComunidadBundle_grupo:
    resource: "@ParroquiaComunidadBundle/Resources/config/routing/grupo.yml"
    prefix:   /grupos  